language: cpp
os: linux
dist: xenial


addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
      - llvm-toolchain-xenial-8
      - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'


env: 
  global: CODE_COVERAGE=false STATIC_ANALYSIS=false


jobs:
  include:
    ################
    # CLANG BUILDS #
    # ver: 7-9     #
    ################
    # - addons: &clang7
        # apt:
          # sources: *apt_sources
          # packages: ["clang-7", "g++-8", "libc++-7-dev", "libc++abi-7-dev", "libstdc++-7-dev"]
      # env: COMPILER_CXX=clang++-7 COMPILER_C=clang-7
      # script: bash ./build.sh
    
    # - addons: &clang8
        # apt:
          # sources: *apt_sources
          # packages: ["clang-8", "g++-8", "libc++-8-dev", "libc++abi-8-dev", "libstdc++-8-dev"]
      # env: COMPILER_CXX=clang++-8 COMPILER_C=clang-8
      # script: bash ./build.sh  
  
    # - addons: &clang9
        # apt:
          # sources: *apt_sources
          # packages: ["clang-9", "g++-9", "libc++-9-dev", "libc++abi-9-dev", "libstdc++-9-dev"]
      # env: COMPILER_CXX=clang++-9 COMPILER_C=clang-9
      # script: bash ./build.sh  
    
    ##############
    # GCC BUILDS #
    # ver: 8-9   #
    ##############   
    # - addons: &gcc8
        # apt:
          # sources: *apt_sources
          # packages: g++-8
      # env: COMPILER_CXX=g++-8 COMPILER_C=gcc-8
      # script: bash ./build.sh  
  
    # - addons: &gcc9
        # apt:
          # sources: *apt_sources
          # packages: ["g++-9"]
      # env: COMPILER_CXX=g++-9 COMPILER_C=gcc-9
      # script: bash ./build.sh  
  
    ##############
    # Misc Tasks #
    ############## 
    # - addons: &code_coverage
        # apt:
          # sources: *apt_sources
          # packages: g++-8
      # env: COMPILER_CXX=g++-8 COMPILER_C=gcc-8 CODE_COVERAGE=true
      # script: bash ./codeCoverage.sh  
  
    - addons: &static_analysis
        apt:
          sources: *apt_sources
          packages: ["clang-9", "clang-tidy-9", "g++-9", "g++-9-multilib", "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386", "libc++-9-dev", "libc++abi-9-dev", "libstdc++-9-dev"]
          update: true
      env: COMPILER_CXX=clang++-9 COMPILER_C=clang-9 STATIC_ANALYSIS=true
      script: bash ./staticAnalysis.sh

 

install:
  # Export Environment Variables
  - export CXX="${COMPILER_CXX}"
  - export CC="${COMPILER_C}"

  # Install Dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - |  
    if [ ${CODE_COVERAGE} = true ]; then
      # Download LCOV
      LCOV_URL="https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-1.14.tar.gz"
      mkdir lcov && travis_retry wget --no-check-certificate -O - ${LCOV_URL} | tar --strip-components=1 -xz -C lcov
      cd lcov
      make install
      export PATH=${DEPS_DIR}/lcov/bin:${PATH}
    fi
    if [[ "${STATIC_ANALYSIS}" = "true" ]]; then
      # Download OCLint
      eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)"   
      # Download latest valgrind
      #wget https://sourceware.org/pub/valgrind/valgrind-3.15.0.tar.bz2 && tar xjf valgrind-3.15.0.tar.bz2 && cd valgrind-3.15.0 && ./configure && make && sudo make install && cd ..
      # Download latest cppcheck
      wget https://github.com/danmar/cppcheck/archive/1.90.tar.gz && tar xjf cppcheck-1.90.tar && cd cppcheck-1.90 && ./configure && make && sudo make install && cd ..
    fi
  
  - cd ${TRAVIS_BUILD_DIR}


before_script:
  - cmake --version
  - cmake ${CMAKE_OPTIONS_GLOBAL} ${CMAKE_OPTIONS} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} . || exit 1